/*
 * Traceability API
 *
 * Provides the ability to create Critical Tracking Events (CTEs), Traceable Resource Units (TRUs) and relate container and their state to TRUs
 *
 * OpenAPI spec version: V1
 * Contact: wg20@aggateway.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ContainerCapacity : IEquatable<ContainerCapacity>
    { 
        /// <summary>
        /// Gets or Sets TypeCode
        /// </summary>

        [DataMember(Name="typeCode")]
        public string TypeCode { get; set; }

        /// <summary>
        /// Gets or Sets MaximumVolumeMeasure
        /// </summary>

        [DataMember(Name="maximumVolumeMeasure")]
        public ContainerCapacityMaximumVolumeMeasure MaximumVolumeMeasure { get; set; }

        /// <summary>
        /// Gets or Sets MaximumWeightMeasure
        /// </summary>

        [DataMember(Name="maximumWeightMeasure")]
        public ContainerCapacityMaximumWeightMeasure MaximumWeightMeasure { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContainerCapacity {\n");
            sb.Append("  TypeCode: ").Append(TypeCode).Append("\n");
            sb.Append("  MaximumVolumeMeasure: ").Append(MaximumVolumeMeasure).Append("\n");
            sb.Append("  MaximumWeightMeasure: ").Append(MaximumWeightMeasure).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ContainerCapacity)obj);
        }

        /// <summary>
        /// Returns true if ContainerCapacity instances are equal
        /// </summary>
        /// <param name="other">Instance of ContainerCapacity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContainerCapacity other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TypeCode == other.TypeCode ||
                    TypeCode != null &&
                    TypeCode.Equals(other.TypeCode)
                ) && 
                (
                    MaximumVolumeMeasure == other.MaximumVolumeMeasure ||
                    MaximumVolumeMeasure != null &&
                    MaximumVolumeMeasure.Equals(other.MaximumVolumeMeasure)
                ) && 
                (
                    MaximumWeightMeasure == other.MaximumWeightMeasure ||
                    MaximumWeightMeasure != null &&
                    MaximumWeightMeasure.Equals(other.MaximumWeightMeasure)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TypeCode != null)
                    hashCode = hashCode * 59 + TypeCode.GetHashCode();
                    if (MaximumVolumeMeasure != null)
                    hashCode = hashCode * 59 + MaximumVolumeMeasure.GetHashCode();
                    if (MaximumWeightMeasure != null)
                    hashCode = hashCode * 59 + MaximumWeightMeasure.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ContainerCapacity left, ContainerCapacity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ContainerCapacity left, ContainerCapacity right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
