/*
 * Traceability API
 *
 * Provides the ability to create Critical Tracking Events (CTEs), Traceable Resource Units (TRUs) and relate container and their state to TRUs
 *
 * OpenAPI spec version: V1
 * Contact: wg20@aggateway.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CriticalTrackingEventListEntryRelatedDatasetMetadataReference : IEquatable<CriticalTrackingEventListEntryRelatedDatasetMetadataReference>
    { 
        /// <summary>
        /// Gets or Sets TypeCode
        /// </summary>

        [DataMember(Name="typeCode")]
        public string TypeCode { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name="id")]
        public List<string> Id { get; set; }

        /// <summary>
        /// Gets or Sets Uri
        /// </summary>

        [DataMember(Name="uri")]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or Sets PublicationDateTime
        /// </summary>

        [DataMember(Name="publicationDateTime")]
        public DateTime? PublicationDateTime { get; set; }

        /// <summary>
        /// Gets or Sets DatasetTypeCode
        /// </summary>

        [DataMember(Name="datasetTypeCode")]
        public string DatasetTypeCode { get; set; }

        /// <summary>
        /// Gets or Sets ProcessCategory
        /// </summary>

        [DataMember(Name="processCategory")]
        public CriticalTrackingEventRequestCreateProcessCategory ProcessCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CriticalTrackingEventListEntryRelatedDatasetMetadataReference {\n");
            sb.Append("  TypeCode: ").Append(TypeCode).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("  PublicationDateTime: ").Append(PublicationDateTime).Append("\n");
            sb.Append("  DatasetTypeCode: ").Append(DatasetTypeCode).Append("\n");
            sb.Append("  ProcessCategory: ").Append(ProcessCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CriticalTrackingEventListEntryRelatedDatasetMetadataReference)obj);
        }

        /// <summary>
        /// Returns true if CriticalTrackingEventListEntryRelatedDatasetMetadataReference instances are equal
        /// </summary>
        /// <param name="other">Instance of CriticalTrackingEventListEntryRelatedDatasetMetadataReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CriticalTrackingEventListEntryRelatedDatasetMetadataReference other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TypeCode == other.TypeCode ||
                    TypeCode != null &&
                    TypeCode.Equals(other.TypeCode)
                ) && 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.SequenceEqual(other.Id)
                ) && 
                (
                    Uri == other.Uri ||
                    Uri != null &&
                    Uri.Equals(other.Uri)
                ) && 
                (
                    PublicationDateTime == other.PublicationDateTime ||
                    PublicationDateTime != null &&
                    PublicationDateTime.Equals(other.PublicationDateTime)
                ) && 
                (
                    DatasetTypeCode == other.DatasetTypeCode ||
                    DatasetTypeCode != null &&
                    DatasetTypeCode.Equals(other.DatasetTypeCode)
                ) && 
                (
                    ProcessCategory == other.ProcessCategory ||
                    ProcessCategory != null &&
                    ProcessCategory.Equals(other.ProcessCategory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TypeCode != null)
                    hashCode = hashCode * 59 + TypeCode.GetHashCode();
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Uri != null)
                    hashCode = hashCode * 59 + Uri.GetHashCode();
                    if (PublicationDateTime != null)
                    hashCode = hashCode * 59 + PublicationDateTime.GetHashCode();
                    if (DatasetTypeCode != null)
                    hashCode = hashCode * 59 + DatasetTypeCode.GetHashCode();
                    if (ProcessCategory != null)
                    hashCode = hashCode * 59 + ProcessCategory.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CriticalTrackingEventListEntryRelatedDatasetMetadataReference left, CriticalTrackingEventListEntryRelatedDatasetMetadataReference right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CriticalTrackingEventListEntryRelatedDatasetMetadataReference left, CriticalTrackingEventListEntryRelatedDatasetMetadataReference right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
