/*
 * Traceability API
 *
 * Provides the ability to create Critical Tracking Events (CTEs), Traceable Resource Units (TRUs) and relate container and their state to TRUs
 *
 * OpenAPI spec version: V1
 * Contact: wg20@aggateway.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CriticalTrackingEventRequestCreateItemInstance : IEquatable<CriticalTrackingEventRequestCreateItemInstance>
    { 
        /// <summary>
        /// Gets or Sets Lot
        /// </summary>

        [DataMember(Name="lot")]
        public List<CriticalTrackingEventRequestCreateLot> Lot { get; set; }

        /// <summary>
        /// Gets or Sets Item
        /// </summary>

        [DataMember(Name="item")]
        public CriticalTrackingEventRequestCreateItem Item { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>

        [DataMember(Name="quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CriticalTrackingEventRequestCreateItemInstance {\n");
            sb.Append("  Lot: ").Append(Lot).Append("\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CriticalTrackingEventRequestCreateItemInstance)obj);
        }

        /// <summary>
        /// Returns true if CriticalTrackingEventRequestCreateItemInstance instances are equal
        /// </summary>
        /// <param name="other">Instance of CriticalTrackingEventRequestCreateItemInstance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CriticalTrackingEventRequestCreateItemInstance other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Lot == other.Lot ||
                    Lot != null &&
                    Lot.SequenceEqual(other.Lot)
                ) && 
                (
                    Item == other.Item ||
                    Item != null &&
                    Item.Equals(other.Item)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Lot != null)
                    hashCode = hashCode * 59 + Lot.GetHashCode();
                    if (Item != null)
                    hashCode = hashCode * 59 + Item.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CriticalTrackingEventRequestCreateItemInstance left, CriticalTrackingEventRequestCreateItemInstance right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CriticalTrackingEventRequestCreateItemInstance left, CriticalTrackingEventRequestCreateItemInstance right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
