/*
 * Traceability API
 *
 * Provides the ability to create Critical Tracking Events (CTEs), Traceable Resource Units (TRUs) and relate container and their state to TRUs
 *
 * OpenAPI spec version: V1
 * Contact: wg20@aggateway.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DeviceResource : IEquatable<DeviceResource>
    { 
        /// <summary>
        /// Gets or Sets DeviceItem
        /// </summary>

        [DataMember(Name="deviceItem")]
        public DeviceResourceDeviceItem DeviceItem { get; set; }

        /// <summary>
        /// Gets or Sets FixedAssetId
        /// </summary>

        [DataMember(Name="fixedAssetId")]
        public string FixedAssetId { get; set; }

        /// <summary>
        /// Gets or Sets FixedAssetCode
        /// </summary>

        [DataMember(Name="fixedAssetCode")]
        public string FixedAssetCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeviceResource {\n");
            sb.Append("  DeviceItem: ").Append(DeviceItem).Append("\n");
            sb.Append("  FixedAssetId: ").Append(FixedAssetId).Append("\n");
            sb.Append("  FixedAssetCode: ").Append(FixedAssetCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DeviceResource)obj);
        }

        /// <summary>
        /// Returns true if DeviceResource instances are equal
        /// </summary>
        /// <param name="other">Instance of DeviceResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeviceResource other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DeviceItem == other.DeviceItem ||
                    DeviceItem != null &&
                    DeviceItem.Equals(other.DeviceItem)
                ) && 
                (
                    FixedAssetId == other.FixedAssetId ||
                    FixedAssetId != null &&
                    FixedAssetId.Equals(other.FixedAssetId)
                ) && 
                (
                    FixedAssetCode == other.FixedAssetCode ||
                    FixedAssetCode != null &&
                    FixedAssetCode.Equals(other.FixedAssetCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DeviceItem != null)
                    hashCode = hashCode * 59 + DeviceItem.GetHashCode();
                    if (FixedAssetId != null)
                    hashCode = hashCode * 59 + FixedAssetId.GetHashCode();
                    if (FixedAssetCode != null)
                    hashCode = hashCode * 59 + FixedAssetCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DeviceResource left, DeviceResource right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DeviceResource left, DeviceResource right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
